# Generated by Django 3.2.12 on 2022-03-04 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coasters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('park', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coasters.park')),
            ],
        ),
    ]
