# Generated by Django 3.2.12 on 2022-03-04 19:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coasters', '0002_coaster'),
    ]

    operations = [
        migrations.AddField(
            model_name='coaster',
            name='date_opened',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
