# Generated by Django 3.2.12 on 2022-03-06 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coasters', '0003_coaster_date_opened'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coaster',
            name='park',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coasters.park'),
        ),
    ]
