# Generated by Django 3.2.12 on 2022-03-07 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coasters', '0004_alter_coaster_park'),
    ]

    operations = [
        migrations.AddField(
            model_name='coaster',
            name='park_string',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
