# Generated by Django 3.2.12 on 2022-03-07 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coasters', '0005_coaster_park_string'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coaster',
            name='date_opened',
            field=models.DateField(null=True),
        ),
    ]
